# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-03-30 17:52
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stackmapmain', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Snippet',
            new_name='Employee',
        ),
    ]
